### PR TITLE
Add private_ip parameter

### PR DESCRIPTION
**Pull request by tzturner**

### CODE REVIEW

**Review by JonRoma — COMMENTED** [review]
@tzturner and @ddriddle, is the `private_ip` parameter a rough equivalent for an EIP, but for private IP space rather than public IP space?

I am curious about what Terraform resource would be used to populate the `private_ip`. Anything you can tell me about your use case would be of interest as well. Thanks.

**Comment by ddriddle** [comment]
@JonRoma Yes, `private_ip` functions similarly to an EIP. No additional resources are needed. No cost either when the box is down. Simply specify the IP desired. From my limited testing it does not seem 100% guaranteed to work. If the IP is already taken the `apply` does not fail it simply creates the EC2 box with another IP. I would have preferred a failure but it does work when the IP is not in use.

Our use case is we need an EC2 box on a campus network to connect to midPoint for development. The IP needs to be stable because midPoint requires a static IP. For SSH login, we locked the box down to the VPN IP block that requires MFA. There is no way to access it via the Internet directly since it has no public IP. It is a pretty secure setup. If you are interested in the config I would be happy to pass it on.

**Review by JonRoma — APPROVED** [review]

**Comment by JonRoma** [comment]
@ddriddle, thanks for the explanation. This has been merged into `main` at tag `v3.1.4`.

Because your use case mentions midPoint, it dawned on me that @akibare999 may be interested in it given her work with midPoint. This feature may prove to be another useful tool in our arsenal.

@ddriddle, please do send the Terragrunt config file to both of us. Regarding the behavior when specifying an IP address that's already assigned, I agree that this is undesirable. Have you dug into it to determine whether this is a shortcoming of the API or if it's a result of Terraform mishandling this case? I would think this should result in an issue being filed. The behavior is not intuitive or desirable.

Thanks to you and @tzturner for improving our modules.

**Comment by ddriddle** [comment]
@JonRoma I think it is an API issue but I did not dig into the issue because it worked well enough.

**Pull request merged**
